/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a standard app. It is checked in here
// so Phase 01 type checking works before the first dev-server run.
